# BASED ON https://github.com/navilg/media-stack

include:
  - services/books.yml
  - services/helpers.yml
  - services/movies.yml
  - services/series.yml
  - services/streaming.yml
  - services/subtitles.yml
  - services/torrent.yml

name: media-server
services:
  # VPN
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: media-server
    environment:
      - TS_AUTHKEY=${TS_AUTH_SERVER}
    cap_add:
      - net_admin
    ports:
      - 80:7575   # homarr
      - 5080:5080 # qbit
      - 7476:7476 # qui
      - 7878:7878 # radarr
      - 7879:7879 # radarr-anime
      - 8989:8989 # sonarr
      - 8990:8990 # sonarr-anime
      - 6767:6767 # bazarr
      - 6768:6768 # bazarr-anime
      - 9696:9696 # prowlarr
      - 5055:5055 # jellyseerr
      - 8096:8096 # jellyfin
      # - 25600:25600 # komga
      # - 8090:8090 # mylar3
      - 8084:8084 # shelfmark
      - 6060:6060 # grimmory
    volumes:
      - ./data/tailscale-config:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: always
